# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt-state-aware-orchestration'
version: '1.0.0'
config-version: 2

dbt-cloud:
    project-id: 514981

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt-state-aware-orchestration'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  dbt-state-aware-orchestration:
    +enabled: true

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# dbt will attempt to create the schemas based on the values defined below.
# If this is not desired you can remove the whole below block.
# dbt will then only use the target schema as defined in the profiles.yml
models:
  dbt-state-aware-orchestration:
    +freshness:
      build_after:
        count: 1
        period: hour
        updates_on: any
    business_vault:
      +schema: core
    control:
      +schema: control
    raw_vault:
      +schema: core
    stages:
      +schema: stages
flags:
  require_generic_test_arguments_property: true